### ISSUE TITLE
Failed to install on windows

### ISSUE THREAD

**Issue by nishray12096** [yannvgn/laserembeddings#16]
Hello,

When trying to install Japanese and Chinese dependencies (pip install laserembeddings[zh,ja]) on windows i'm seeing an error: 

![image](https://user-images.githubusercontent.com/35083698/71682858-c50a4780-2d45-11ea-9c38-6386fc59729a.png)

The same error occurs when trying to install mecab-python3 directly. I've installed mecab and the frozen environment is attached.
[requirements.txt](https://github.com/yannvgn/laserembeddings/files/4016841/requirements.txt)
 
EDIT: Have also installed mecab-python-windows but get the same error when installing laserembeddings for chinese and japanese.

EDIT 2: This error only occurs when installing for Japenese or Chinese, but seems like it results in an issue with all languages. In english, retrieving embeddings gives the following MeCab related error:
![image](https://user-images.githubusercontent.com/35083698/71691824-34d7fc80-2d5d-11ea-8f90-6b61cebabcf6.png)

Thanks in advance :)

**Comment by yannvgn** [comment]
Hi @nishray12096,

Thanks for your feedback. Mecab-python3 does not provide wheels for windows (https://github.com/SamuraiT/mecab-python3/issues/31) and it looks like there's no easy solution for Windows for now (I mean without having to install Mecab separately or without compiling).

As a quick fix, I will disable Japanese extra on windows until wheels are available for windows. I will also implement a fix that will prevent Laser from complaining when mecab-python3 was installed but is not working.

Cheers
