### ISSUE TITLE
Pickle data was truncated

### ISSUE THREAD

**Issue by prakharlovesdata** [yannvgn/laserembeddings#22]
530 
    531 

/opt/conda/lib/python3.6/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    700     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    701     unpickler.persistent_load = persistent_load
--> 702     result = unpickler.load()
    703 
    704     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

UnpicklingError: pickle data was truncated

**Comment by yannvgn** [comment]
Hi Prakhar,

Please provide some more context about the issue, otherwise I won't be able to help you.
