### ISSUE TITLE
Getting version error related to torch

### ISSUE THREAD

**Issue by shrutibhutaiya** [yannvgn/laserembeddings#25]
while installing : getting an error related to version of torch required. 

![image](https://user-images.githubusercontent.com/10259707/85017116-9879a900-b188-11ea-8b26-38edd57ea65f.png)

**Comment by yannvgn** [comment]
Hi,

Ah yeah, PyTorch is not available for Windows through pypi. You'll have to manually install PyTorch first, then you'll be able to install laserembeddings.

Please follow the installation instructions here: https://pytorch.org/get-started/locally/.

I will add a note in the README.

Thanks for the feedback!

**Comment by yannvgn** [comment]
I've included a note on PyTorch installation in the README.

I'm closing the issue. Feel free to re-open it if needed.
