### ISSUE TITLE
AttributeError: 'BPECodesAdapter' object has no attribute 'read'

### ISSUE THREAD

**Issue by NikolaiG-A** [yannvgn/laserembeddings#38]
I've recently experienced this error `AttributeError: 'BPECodesAdapter' object has no attribute 'read'` which comes from the package _subword_nmt_ used during the tokenization. Apparently, this package had some modifications. It's better to fix the specific version during installation of laserembeddings to avoid the problem, i.e.  `pip install subword-nmt==0.3.7`

**Comment by AghilesAzzoug** [comment]
Hi mate! :wave:

**Comment by yannvgn** [comment]
Thanks for reporting the issue, @NikolaiG-A, and sorry for that.
The fix was released, you can now upgrade to 1.1.2.

Cheers,
