### ISSUE TITLE
Upgrade or make new laserembeddings branch for Laser2 and Laser3 models

### ISSUE THREAD

**Issue by Fikavec** [yannvgn/laserembeddings#43]
Hello!
First of all, thank you very much for this pretty light and simple for use laser model fork.
Do you have any plans to update laserembeddings to [new LASER2 and LASER3 models?](https://github.com/facebookresearch/LASER/blob/main/nllb/README.md)
For face-to-face comparison laserembeddings and original model this dataset can also be used: [flores-101 or flores-200 dataset](https://github.com/facebookresearch/flores)
Cheers!

**Comment by Treparme** [comment]
I'm one of the founders of Tekst.ai, an NLP startup that utilizes laser in some of our products.

**We are finalizing the building of our pip package that utilizes LASER2 and LASER3 and are willing to opensource it :)**

Give me a headsup if you are looking for something like this, we might do some tests with beta users first to fix final issues.

LASER rocks, letsgo 

** update
Building on: https://github.com/Tekst-ai/LASERembedding

**Comment by jgcb00** [comment]
Hi, 
We release an easy to install, easy to use, laser package. 
it supports Laser2 - Laser3, you can choose your hardware, and it support multiprocessing out of the box.
You can embeds sentences and align them,
everything is well explain here : 
[https://gitlab.com/linguacustodia/easylaser](https://gitlab.com/linguacustodia/easylaser)
